DROP TABLE IF EXISTS member_notification;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS role_account;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS family_member;
DROP TABLE IF EXISTS family; 